name: creek
author: Diego Rocha <diego.rocha.comp@gmail.com>
version: 0.1.0
homepage: https://github.com/Dreckr/Creek
description: A simple http server routing system.
environment:
  sdk: '>=1.0.0'
dev_dependencies:
  unittest: '>=0.5.16'
