name: creek
version: 0.0.2
author: Diego Rocha <diego.rocha.comp@gmail.com>
description: A simple http server routing system.
homepage: https://github.com/Dreckr/Creek
environment:
  sdk: '>=0.5.16'
dev_dependencies:
  unittest: '>=0.4.7'
