name: creek
version: 0.0.1
author: Diego Rocha
description: A simple web development framework with Sinatra looks and Dart power.
homepage: https://github.com/Dreckr/Creek
environment:
  sdk: '>=0.4.7'
dev_dependencies:
  unittest: '>=0.4.7'
