name: creek
version: 0.0.1-beta
author: Diego Rocha <diego.rocha.comp@gmail.com>
description: A simple web development framework with Sinatra looks and Dart power.
homepage: https://github.com/Dreckr/Creek
environment:
  sdk: '>=0.4.7'
dev_dependencies:
  unittest: '>=0.4.7'
